apiVersion: v1
kind: Pod
metadata:
  name: tcp-socket
  labels:
    app: tcp-socket
spec:
  containers:
  - name: tcp
    image: dawood6/paintswebpage:latest
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
